Author Api : Friend List of Author & Retrieve Author's Profile
CMPUT404W20/CMPUT404-project-socialdistribution pull request #65
Opened 2020-02-27 06:15 UTC by sandysaji

Pull Request Content:

- API that takes in author_id to retrieve the author's friend list: /author/{author_id}/friends:
- API that takes in author id to retrieve the author's profile: /author/{author_id}:

Changes made to Serializer.py
Added Test Cases for each API.

The response from test_get_friends() has ordered Dict inside ordered Dict. Not sure if this should be the output. Please take a look.

Please review the changes made, and feel free to suggest any changes necessary

2020-03-05 04:42 UTC, zhaoyuxuan commented on backend/apiviews/author_views.py
> +    def get_object(self, pk):
No need to include this function as Viewset comes with this function by default already

2020-03-05 04:43 UTC, zhaoyuxuan commented on backend/tests/test_author_api.py
> +    @pytest.fixture
please move this to `conftest.py` so that it can be used across all the tests

2020-03-05 05:10 UTC, zhaoyuxuan requested changes
A few changes needed:
1. Currently, response from GET `/author/{author_id}/friends` doesn't follow the format they asked for
2. Move the fixture to `conftest.py`
3. Clean up the code, fix the spacing, remove useless comments
4. Try to clean up the tests

2020-03-05 05:10 UTC, zhaoyuxuan commented on backend/tests/test_author_api.py
> +        # print(test_friend.toUser)
remove useless comments

2020-03-08 00:40 UTC, sandysaji commented on backend/tests/test_author_api.py
> +        # print(test_friend.toUser)
Done!

2020-03-08 06:17 UTC, zhaoyuxuan submitted a review, later dismissed

2020-03-08 22:31 UTC, zhaoyuxuan approved these changes

2020-03-08 22:45 UTC, merged